spring:
  application:
    name: LibraryManagSys

  h2:
    console:
      path: /console
      enabled: true

  datasource:
    username: sa
    password: 1234
    url: jdbc:h2:mem:library

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      schema-locations: classpath:sql-data/schema.sql # specify your schema-path here, inside sql-data folder
      data-locations: classpath:sql-data/import.sql # specify your data-path here